services:
  backend:
    container_name: eshop_service_name
    image: service_name  # This can be omitted.
    build:
      context: ../
      dockerfile: .
    environment:
      - POSTGRES_HOST=postgres-db
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '8080:${SERVICE_PORT}'
  db:
    container_name: postgres-db
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5432:${POSTGRES_PORT}'
