# Connects the service to postgresql and setup hibernate automatic database migrations.
spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: "org.postgresql.Driver"
  jpa.open-in-view: false

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
