name: Publish Scratch-JRE Images

on:
  workflow_dispatch:
  push:
    tags: [ '**' ]
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  docker_lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file: ["scratch-jre/jre.dockerfile", "scratch-jre/jre-fonts.dockerfile"]

    steps:
      - uses: actions/checkout@v3.3.0

      - name: "Scan ${{ matrix.file }}"
        uses: hadolint/hadolint-action@master
        id: hadolint
        with:
          dockerfile: ${{ matrix.file }}
          verbose: true
          failure-threshold: warning

      - name: "${{ matrix.file }} results"
        run: |
          echo Hadolint: ${{ steps.hadolint.outcome }}
          echo ${{ env.HADOLINT_RESULTS }}
          if [ ${{ steps.hadolint.outcome }} != "success" ];then
            exit 1
          fi

  push_to_registry:
    needs: docker_lint
    strategy:
      matrix:
#        version: [17, 19]
        size: [min, max]
        file: ["", fonts]
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    continue-on-error: false

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3.3.0

      - run: |
          if [ "${{ matrix.file }}" = "" ]
          then
            file=""
          else
            file="-${{ matrix.file }}"
          fi
          echo "file=$file" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5.0.0
        with:
          context: scratch-jre
          push: true
          file: scratch-jre/jre${{ env.file }}.dockerfile
          build-args: |
            JAVA_VER: 17
            JRE_SIZE: ${{ matrix.size }}
          tags: aminadaven/scratch-jre:${{ matrix.size }}-${{ matrix.version }}${{ env.file }}
